Repository SSGorg/Cryptex, pull requests merged in 2022-10, with the labels that each got.

#9 Add input and output function
  src/main.py
Labels: hacktoberfest-accepted

#14 Added Multiplicative Cipher
  src/cipher/ciphers/__init__.py
  src/cipher/ciphers/mc.py
Labels: hacktoberfest-accepted

#16 add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#18 Added menc cipher
  src/cipher/ciphers/__init__.py
  src/cipher/ciphers/menc.py
Labels: hacktoberfest-accepted

#22 Added CODE_OF_CONDUCT file
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#41 Updating
  install.py
  requirements.txt
  src/__init__.py
  src/main.py
  src/update.py
  src/vars.py
  version
Labels: enhancement, hacktoberfest-accepted

#42 Autokey cipher
  src/cipher/ciphers/__init__.py
  src/cipher/ciphers/ak.py
Labels: enhancement, help wanted, hacktoberfest-accepted

#33 feat: Baconian Cipher
  src/cipher/ciphers/__init__.py
  src/cipher/ciphers/bac.py
Labels: enhancement, hacktoberfest-accepted

#50 add gaderypoluki.py
  src/cipher/ciphers/__init__.py
  src/cipher/ciphers/gc.py
  src/update.py
Labels: enhancement, help wanted, hacktoberfest-accepted

#52 cryoads setup
  cryoads/loki/loki.py
  src/test.png
Labels: enhancement

#53 loki resolves
  cryoads/loki/loki.py
Labels: bug, enhancement

#56 Contributors section feature added into README.md
  README.md
Labels: enhancement, help wanted, hacktoberfest-accepted

#61 Made lots of tweaks to the grammar, spellings, and made the overall text sound more concise.
  CONTRIBUTING.md
  README.md
Labels: enhancement, hacktoberfest-accepted

#47 add tests
  requirements.txt
  src/cipher/cipher.py
  src/cipher/ciphers/L33T.py
  src/cipher/ciphers/b64.py
  src/cipher/ciphers/bin.py
  src/cipher/ciphers/cc.py
  src/cipher/ciphers/hex.py
  src/cipher/ciphers/mor.py
  src/cipher/ciphers/oct.py
  src/cipher/ciphers/r13.py
  src/cipher/ciphers/r47.py
  src/cipher/ciphers/rc.py
  src/cipher/ciphers/text.py
  src/cipher/ciphers/translate.py
  src/cipher/ciphers/vig.py
  src/cipher/ciphers/xor.py
  src/controller.py
Labels: enhancement, help wanted, hacktoberfest-accepted

#66 feat: Add Affine Cipher
  src/cipher/ciphers/__init__.py
  src/cipher/ciphers/affn.py
  src/controller.py
Labels: enhancement, hacktoberfest-accepted

#67 feat: Add Playfair Cipher
  src/cipher/ciphers/__init__.py
  src/cipher/ciphers/pf.py
Labels: enhancement, hacktoberfest-accepted

#46 V:1.0.0 Pumpkin Patch
  CONTRIBUTING.md
  README.md
  requirements.txt
  src/cipher/cipher.py
  src/cipher/ciphers/L33T.py
  src/cipher/ciphers/__init__.py
  src/cipher/ciphers/affn.py
  src/cipher/ciphers/b64.py
  src/cipher/ciphers/bin.py
  src/cipher/ciphers/cc.py
  src/cipher/ciphers/gc.py
  src/cipher/ciphers/hex.py
  src/cipher/ciphers/mor.py
  src/cipher/ciphers/oct.py
  src/cipher/ciphers/pb.py
  src/cipher/ciphers/pf.py
  src/cipher/ciphers/r13.py
  src/cipher/ciphers/r47.py
  src/cipher/ciphers/rc.py
  src/cipher/ciphers/sha224.py
  src/cipher/ciphers/sha256.py
  src/cipher/ciphers/sha384.py
  src/cipher/ciphers/text.py
  src/cipher/ciphers/translate.py
  src/cipher/ciphers/vig.py
  src/cipher/ciphers/xor.py
  src/controller.py
  src/update.py
  src/vars.py
  version
Labels: enhancement, help wanted, hacktoberfest-accepted
